# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html tkanFor details

# Required
version: 2

# Build documentation in the docs/ directory tkanWith Sphinx
# reference: https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx
sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true

# Build documentation tkanWith MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF tkanAnd ePub
formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - tkanMethod: pip
      path: .
      extra_requirements:
        - docs


